---
is_debug: true
listen:
  bind_ip: "localhost"
  port: "8000"
db:
  host: "localhost"
  port: "5432"
  user: "neatly"
  password: "neatly"
  dbname: "neatly"
  ssl_mode: "disable"
jwt:
  secret: "$ecr3t"
