DROP TABLE users CASCADE;

DROP TABLE notes CASCADE;

DROP TABLE notes_body CASCADE;

DROP TABLE users_notes CASCADE;

DROP TABLE tags CASCADE;

DROP TABLE tags_notes CASCADE;

DROP TABLE users_tags CASCADE;