basePath: /
definitions:
  dto.CreateNoteDTO:
    properties:
      body:
        type: string
      color:
        type: string
      header:
        type: string
    required:
    - color
    - header
    type: object
  dto.CreateTagDTO:
    properties:
      label:
        type: string
    required:
    - label
    type: object
  dto.GetAccountDTO:
    properties:
      email:
        type: string
      name:
        type: string
      username:
        type: string
    type: object
  dto.GetAllNotesDTO:
    properties:
      notes:
        items:
          $ref: '#/definitions/model.Note'
        type: array
    type: object
  dto.GetAllTagsDTO:
    properties:
      tags:
        items:
          $ref: '#/definitions/model.Tag'
        type: array
    type: object
  dto.LoginAccountDTO:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  dto.RegisterAccountDTO:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  dto.UpdateNoteDTO:
    properties:
      body:
        type: string
      color:
        type: string
      header:
        type: string
      id:
        type: integer
    type: object
  dto.UpdateTagDTO:
    properties:
      label:
        type: string
    type: object
  dto.WithTokenDTO:
    properties:
      email:
        type: string
      name:
        type: string
      token:
        type: string
      username:
        type: string
    type: object
  e.ErrorResponse:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  model.Note:
    properties:
      body:
        type: string
      color:
        type: string
      edited:
        type: string
      header:
        type: string
      id:
        type: integer
      tags:
        items:
          $ref: '#/definitions/model.Tag'
        type: array
    type: object
  model.Tag:
    properties:
      id:
        type: integer
      label:
        type: string
    required:
    - label
    type: object
info:
  contact: {}
  description: API Server for notes-taking applications
  termsOfService: http://swagger.io/terms/
  title: Neat.ly API
  version: "1.0"
paths:
  /api/v1/accounts/{id}:
    get:
      consumes:
      - application/json
      description: get account
      operationId: get-account
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetAccountDTO'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: GetAccount
      tags:
      - account
  /api/v1/accounts/login:
    post:
      consumes:
      - application/json
      description: login
      operationId: login
      parameters:
      - description: credentials
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/dto.LoginAccountDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.WithTokenDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      summary: Login
      tags:
      - account
  /api/v1/accounts/register:
    post:
      consumes:
      - application/json
      description: create account
      operationId: create-account
      parameters:
      - description: account info
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterAccountDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      summary: RegisterAccount
      tags:
      - account
  /api/v1/notes:
    get:
      consumes:
      - application/json
      description: create note
      parameters:
      - description: notes search by tag
        in: query
        name: tag
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetAllNotesDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get all notes from user filter by tag
      tags:
      - notes
    post:
      consumes:
      - application/json
      description: create note
      parameters:
      - description: note content
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/dto.CreateNoteDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Create note
      tags:
      - notes
  /api/v1/notes/{id}:
    delete:
      consumes:
      - application/json
      description: delete note
      operationId: delete-note
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Delete Note
      tags:
      - notes
    get:
      consumes:
      - application/json
      description: get note by id
      operationId: get-note-by-id
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Note'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get Note By id
      tags:
      - notes
    patch:
      consumes:
      - application/json
      description: update note
      operationId: update-note
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: note content
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateNoteDTO'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Update Note
      tags:
      - notes
  /api/v1/notes/{id}/tags:
    get:
      consumes:
      - application/json
      description: get tags for note
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetAllTagsDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get all tags on one note
      tags:
      - tags
    post:
      consumes:
      - application/json
      description: create tag
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: tag info
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/dto.CreateTagDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Create tag
      tags:
      - tags
  /api/v1/tags:
    get:
      consumes:
      - application/json
      description: get tags from user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetAllTagsDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get all tags
      tags:
      - tags
  /api/v1/tags/{id}:
    delete:
      consumes:
      - application/json
      description: delete one tag by ID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Delete one tag by ID
      tags:
      - tags
    get:
      consumes:
      - application/json
      description: get one tag by ID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Tag'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get one tag by ID
      tags:
      - tags
    patch:
      consumes:
      - application/json
      description: update one tag by ID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: tag info
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateTagDTO'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Update tag by ID
      tags:
      - tags
  /api/v1/tags/{note_id}/tags/{tag_id}:
    delete:
      consumes:
      - application/json
      description: detach tag by ID from note by ID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: tag id
        in: path
        name: tag_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Detach tag by ID from note by ID
      tags:
      - tags
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
