name: build-and-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: go build -o app ./cmd/main/main.go

      - name: Unit tests
        run: go test -v ./... -tags=unit

      - name: Unit tests
        run: go test -v ./... -tags=integration

      - name: E2E tests
        run: go test -v ./... -tags=e2e
