name: build-and-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Get dependencies
        run: |
          cd backend
          go mod download

      - name: Build
        run: |
          cd backend
          go build -o app ./cmd/main/main.go

      - name: Unit tests
        run: |
          docker-compose up -d testdb
          cd backend
          go test -v ./... -tags=unit
          cd ..
          docker-compose down

      - name: Integration tests
        run: |
          docker-compose up -d testdb
          cd backend
          go test -v ./... -tags=integration
          cd ..
          docker-compose down

      - name: E2E tests
        run: |
          docker-compose up -d testdb
          cd backend
          go test -v ./... -tags=e2e
          cd ..
          docker-compose down
