name: build-and-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Get dependencies
        run: |
          cd backend
          go mod download

      - name: Build
        run: |
          cd backend
          go build -o app ./cmd/main/main.go

      - name: Unit tests
        run: |
          docker-compose up -d testdb
          sleep 10s
          cd backend/internal/service
          go test -v account/*
          go test -v note/*
          go test -v tag/*
          cd ../repository/psql_test
          go test -v psql* 
          docker-compose down

      - name: Integration tests
        run: |
          docker-compose up -d testdb
          sleep 10s
          cd backend/internal/service
          go test -v service_integration_test.go
          cd ..
          docker-compose down

      - name: E2E tests
        run: |
          docker-compose up -d testdb
          sleep 10s
          cd backend/internal
          go test e2e_test.go
          cd ..
          docker-compose down
